//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoversenySzimulator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Race
    {
        public int RaceID { get; set; }
        public int H1 { get; set; }
        public int J1 { get; set; }
        public int H2 { get; set; }
        public int J2 { get; set; }
        public int H3 { get; set; }
        public int J3 { get; set; }
        public int H4 { get; set; }
        public int J4 { get; set; }
        public int H5 { get; set; }
        public int J5 { get; set; }
    
        public virtual Hors Hors { get; set; }
        public virtual Hors Hors1 { get; set; }
        public virtual Hors Hors2 { get; set; }
        public virtual Hors Hors3 { get; set; }
        public virtual Hors Hors4 { get; set; }
        public virtual Jockey Jockey { get; set; }
        public virtual Jockey Jockey1 { get; set; }
        public virtual Jockey Jockey2 { get; set; }
        public virtual Jockey Jockey3 { get; set; }
        public virtual Jockey Jockey4 { get; set; }
    }
}
